name: launch_review
version: 3.0.1
homepage: https://github.com/purus/launch_review/
publish_to: https://onepub.dev/api/xpdpsdavuh/
description: A Flutter plugin to assist in leaving user reviews/ratings in Google Play Store and Apple App Store.
environment: 
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=1.20.0'
dependencies: 
  flutter: 
    sdk: flutter
flutter: 
  plugin: 
    platforms: 
      android: 
        package: com.iyaffle.launchreview
        pluginClass: LaunchReviewPlugin
      ios: 
        pluginClass: LaunchReviewPlugin
